├── src
│   ├── index.html
│   ├── css
│   │   ├── style.css
│   │   ├── utilities.css
│   ├── assets
│   │   ├── favicon
│   │   │   ├── android-chrome-192x192
│   │   │   ├── android-chrome-512x512
│   │   │   ├── apple-touch-icon
│   │   │   ├── favicon-16x16
│   │   │   ├── favicon-32x32
│   │   │   ├── favicon.ico
│   │   │   ├── site.webmanifest   
│   │   ├── profile-image
│   │   ├── logo
│   ├── js
│   │   ├── script.js
├── .github
│   ├── ISSUE_TEMPLATE
│   │   ├── bug.md
│   │   ├── feature.md
│   ├── Pull_request_template.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── REQUIREMENTS.md
├── package.json
└── .gitignore

<!-- Logo -->
<h1 id="logo">
    <a href="#"><img src="./assets/logo.png" alt="Your Logo"></a>
</h1>
<ul class="nav-menu">
   <li><a class="nav-link" href="#">PROJECTS</a></li>
   <li><a class="nav-link" href="#">CONTACT</a></li>
   <li><a class="nav-link" href="#">BlOG</a></li>
   <li><a class="nav-link btn btn-primary" href="#">RESUME <i class="fas fa-arrow-right"></i></a>
   </li>     
</ul>
<img class="profile-image" src="./assets/profile-image.png" alt="" />
<h1>Hi I'm Gowtham</h1>
<h2>Building digital</h2>
<h2>products, brands, and experience.</h2>
<p>
  A Frontend Developer and Visual Designer with experience in web
  design, brand identity and product design.
</p>
<a href="#" class="btn btn-secondary">Connect With Me</a>
<div href="" class="card">
   <div class="project-info">
      <div class="project-bio">
         <h3>Project One</h3>
         <p>React, Redux, SASS</p>
      </div>

      <div class="project-link">
         <a href="#"><i class="fab fa-github"></i></a>
         <a href="#"><i class="fas fa-globe"></i></a>
      </div>
   </div>
</div>
<h3>Project One</h3>

